version: '3.8'
services:
  mysql-db:
    image: mysql:8.0
    volumes:
      - ./mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_USER: autos
      MYSQL_PASSWORD: autos2024
      MYSQL_DATABASE: autos_db

  app:
    build:
      context: ./gpds-autos
      dockerfile: Dockerfile
    ports:
      - "8082:8083"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/autos_db
      SPRING_DATASOURCE_USERNAME: autos
      SPRING_DATASOURCE_PASSWORD: autos2024
      SPRING_JPA_HIBERNATE_DDL_AUTO: create
    depends_on:
      - mysql-db